spring:
  application:
    name: observableApp
  datasource:
    url: jdbc:postgresql://localhost:5432/observableApp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
    diskspace:
      enabled: true
    db:
      enabled: true
    ping:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
