spring:
  application:
    name: observableApp
  datasource:
    url: jdbc:postgresql://localhost:5432/observableApp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,metrics"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
    diskspace:
      enabled: true
    db:
      enabled: true
    ping:
      enabled: true
  metrics:
    tags:
      application: observable-app
    enable:
      all: true
      jvm: true
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.75, 0.9, 0.95, 0.99
      percentiles-histogram:
        http.server.requests: true
      sla:
        http.server.requests: 50ms, 100ms, 200ms, 300ms, 500ms, 1s
    export:
      prometheus:
        enabled: true