global:
  scrape_interval: 5s

scrape_configs:

- job_name: prometheus-observable-app
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - prometheus-observable-app:9090

- job_name: observable-app
  metrics_path: /actuator/prometheus
  static_configs:
  - targets:
    - app-forum-api:8080
