{
 "title": "dash-observable-app",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{application=\"${application}\"}, instance)"
    }
   },
   {
    "name": "pool",
    "label": "pool",
    "query": {
     "query": "label_values(hikaricp_connections{instance=\"$instance\", application=\"$application\"}, pool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "API RED",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "REQUEST TOTAL/M",
   "type": "stat",
   "description": "Número de request no ultimo minuto",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"observable-app\", uri!=\"/actuator/prometheus\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response TIME",
   "type": "timeseries",
   "description": "tempo de resposta no ultimo minuto",
   "gridPos": { "h": 8, "w": 11, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"observable-app\", uri!=\"/actuator/prometheus\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"observable-app\", uri!=\"/actuator/prometheus\"}[1m])",
     "legendFormat": "{{uri}} {{method}} {{status}}"
    }
   ]
  },
  {
   "title": "ERROR 500",
   "type": "stat",
   "description": "Numero de erros 500 no ultimo momento",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"observable-app\", uri!=\"/actuator/prometheus\", status=\"500\"}[1m]))",
     "legendFormat": "500"
    }
   ]
  },
  {
   "title": "ERROR RATE",
   "type": "timeseries",
   "description": "Taxa de erros nos ultimos 5 minutos",
   "gridPos": { "h": 6, "w": 11, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"observable-app\", uri!=\"/actuator/prometheus\", status=\"500\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"observable-app\", uri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "500"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"observable-app\", uri!=\"/actuator/prometheus\", status=\"400\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"observable-app\", uri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "400"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"observable-app\", uri!=\"/actuator/prometheus\", status=\"404\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"observable-app\", uri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "404"
    }
   ]
  },
  { "title": "DATABASE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "DB CONNECTION TIMEOUT",
   "type": "stat",
   "description": "conexões em timeout",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hikaricp_connections_timeout_total{application=\"$application\", instance=\"$instance\", job=\"observable-app\", pool=\"$pool\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CONNECTION STATE",
   "type": "timeseries",
   "description": "Estado das conexões com o databse",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hikaricp_connections_active{ application=\"$application\", instance=\"$instance\", job=\"observable-app\", pool=\"$pool\"}",
     "legendFormat": "active"
    },
    {
     "expr": "hikaricp_connections_idle{ application=\"$application\", instance=\"$instance\", job=\"observable-app\", pool=\"$pool\"}",
     "legendFormat": "idle"
    },
    {
     "expr": "hikaricp_connections_pending{ application=\"$application\", instance=\"$instance\", job=\"observable-app\", pool=\"$pool\"}",
     "legendFormat": "pending"
    }
   ]
  },
  { "title": "API BASIC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "User Created",
   "type": "stat",
   "description": "Usuarios criados",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "USER_CREATED_total{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Deleted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "USER_DELETED_total{application=\"observable-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WARN & ERROR LOG",
   "type": "timeseries",
   "description": "Warning e erros logados nos ultimos 5 munitos",
   "gridPos": { "h": 13, "w": 10, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(logback_events_total{application=\"$application\", instance=\"$instance\", job=\"observable-app\",level=\"warn\"}[5m])",
     "legendFormat": "{{level}}"
    },
    {
     "expr": "increase(logback_events_total{application=\"$application\", instance=\"$instance\", job=\"observable-app\",level=\"error\"}[5m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Request errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "USER_DELETED_total{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users find",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "USER_FIND_total{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Updated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "USER_UPDATED_total{application=\"observable-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPTIME",
   "type": "stat",
   "description": "API Uptime",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\", job=\"observable-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "START TIME",
   "type": "stat",
   "description": "hora da inicialização da API.",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\", job=\"observable-app\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}